// ─── Constants ───────────────────────────────────────────────────────────────

export const DAYS = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];

export const SOUND_OPTIONS = [
  { value: 'default', label: 'Default' },
  { value: 'none',    label: 'None (silent)' },
  { value: 'beep',    label: 'Beep' },
  { value: 'chime',   label: 'Chime' },
  { value: 'alert',   label: 'Alert' },
  { value: 'gentle',  label: 'Gentle' },
];

// ─── Category Colors ──────────────────────────────────────────────────────────

export const CATEGORY_COLORS = {
  'Breakfast':        '#FDE68A',
  'Lunch':            '#FCD34D',
  'Dinner':           '#F59E0B',
  'Meal Prep':        '#FBBF24',
  'Snack':            '#FEF3C7',
  'Hygiene':          '#BAE6FD',
  'Morning Routine':  '#7DD3FC',
  'Evening Routine':  '#38BDF8',
  'Sleep':            '#1E40AF',
  'Meditation':       '#C4B5FD',
  'Journaling':       '#DDD6FE',
  'Study':            '#6EE7B7',
  'Research':         '#34D399',
  'Research Paper':   '#10B981',
  'Chinese Practice': '#059669',
  'Schola Nova':      '#047857',
  'Lecture':          '#A7F3D0',
  'Tutorial':         '#6EE7B7',
  'Lab':              '#34D399',
  'Exam Prep':        '#065F46',
  'Deep Work':        '#818CF8',
  'Shallow Work':     '#A5B4FC',
  'Emails':           '#C7D2FE',
  'Meetings':         '#6366F1',
  'Client Call':      '#4F46E5',
  'Content Creation': '#7C3AED',
  'Career':           '#5B21B6',
  'Planning':         '#8B5CF6',
  'Admin':            '#DDD6FE',
  'Xipu Project':     '#4338CA',
  'Data Collection':  '#3730A3',
  'Gym':              '#FB923C',
  'Cardio':           '#F97316',
  'Run':              '#EA580C',
  'Yoga':             '#FDBA74',
  'Stretching':       '#FED7AA',
  'Recovery':         '#FEF3C7',
  'Football':         '#DC2626',
  'Football Training':'#EF4444',
  'Calisthenics':     '#F87171',
  'Back/Biceps':      '#FCA5A5',
  'Legs/Abs':         '#FECACA',
  'Chest/Shoulders/Triceps': '#FEE2E2',
  'Childcare':        '#F9A8D4',
  'School Run':       '#F472B6',
  'Cooking':          '#EC4899',
  'Cleaning':         '#DB2777',
  'Family Time':      '#BE185D',
  'Errands':          '#FBCFE8',
  'Adventure':        '#FCD34D',
  'Reading':          '#86EFAC',
  'Gaming':           '#4ADE80',
  'Free Time':        '#BBF7D0',
  'Social':           '#6EE7B7',
};

// ─── Default Built-in Templates ───────────────────────────────────────────────
// isDefault: true means these cannot be deleted by the user.

export const DEFAULT_TEMPLATES = [
  {
    id: 'blank',
    name: 'Blank Schedule',
    description: 'Start from scratch',
    icon: '✏️',
    color: '#94A3B8',
    isDefault: true,
    events: [],
  },
  {
    id: 'student',
    name: 'Student',
    description: 'Classes, study & balance',
    icon: '🎓',
    color: '#6366F1',
    isDefault: true,
    events: [
      { day:'Monday',    start:'07:30', end:'08:00', title:'Morning Routine', color:'#7DD3FC', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'08:00', end:'08:30', title:'Breakfast',       color:'#FDE68A', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'09:00', end:'11:00', title:'Lecture',         color:'#6EE7B7', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'11:00', end:'13:00', title:'Study',           color:'#6EE7B7', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'13:00', end:'14:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'14:00', end:'16:00', title:'Tutorial',        color:'#6EE7B7', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'16:00', end:'18:00', title:'Study',           color:'#6EE7B7', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'18:00', end:'19:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'20:00', end:'22:00', title:'Study',           color:'#6EE7B7', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'09:00', end:'12:00', title:'Lab',             color:'#34D399', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'13:00', end:'14:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'14:00', end:'17:00', title:'Study',           color:'#6EE7B7', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'17:30', end:'19:00', title:'Gym',             color:'#FB923C', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'19:00', end:'20:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'09:00', end:'11:00', title:'Lecture',         color:'#6EE7B7', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'11:00', end:'13:00', title:'Study',           color:'#6EE7B7', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'13:00', end:'14:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'14:00', end:'17:00', title:'Research',        color:'#10B981', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'19:00', end:'21:00', title:'Free Time',       color:'#BBF7D0', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'09:00', end:'12:00', title:'Lecture',         color:'#6EE7B7', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'13:00', end:'14:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'14:00', end:'17:00', title:'Study',           color:'#6EE7B7', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'17:30', end:'19:00', title:'Gym',             color:'#FB923C', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'19:00', end:'20:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'09:00', end:'11:00', title:'Lecture',         color:'#6EE7B7', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'13:00', end:'14:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'14:00', end:'16:00', title:'Exam Prep',       color:'#065F46', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'19:00', end:'22:00', title:'Social',          color:'#6EE7B7', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Saturday',  start:'10:00', end:'12:00', title:'Study',           color:'#6EE7B7', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Saturday',  start:'14:00', end:'16:00', title:'Free Time',       color:'#BBF7D0', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Sunday',    start:'10:00', end:'12:00', title:'Study',           color:'#6EE7B7', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Sunday',    start:'14:00', end:'17:00', title:'Free Time',       color:'#BBF7D0', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
    ],
  },
  {
    id: 'professional',
    name: 'Professional',
    description: '9–5 with deep work',
    icon: '💼',
    color: '#0EA5E9',
    isDefault: true,
    events: [
      { day:'Monday',    start:'06:30', end:'07:30', title:'Morning Routine', color:'#7DD3FC', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'08:00', end:'09:00', title:'Commute',         color:'#CBD5E1', notify:true,  notifyBefore:15, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'09:00', end:'11:30', title:'Deep Work',       color:'#818CF8', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'11:30', end:'12:00', title:'Emails',          color:'#C7D2FE', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'13:00', end:'14:00', title:'Meetings',        color:'#6366F1', notify:true,  notifyBefore:5,  sound:'default', soundEnabled:true },
      { day:'Monday',    start:'14:00', end:'16:30', title:'Deep Work',       color:'#818CF8', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'16:30', end:'17:00', title:'Emails',          color:'#C7D2FE', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'17:00', end:'18:00', title:'Commute',         color:'#CBD5E1', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'19:00', end:'20:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'08:00', end:'09:00', title:'Commute',         color:'#CBD5E1', notify:true,  notifyBefore:15, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'09:00', end:'11:30', title:'Deep Work',       color:'#818CF8', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'13:00', end:'15:00', title:'Meetings',        color:'#6366F1', notify:true,  notifyBefore:5,  sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'15:00', end:'17:00', title:'Deep Work',       color:'#818CF8', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'17:00', end:'18:00', title:'Commute',         color:'#CBD5E1', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'09:00', end:'12:00', title:'Deep Work',       color:'#818CF8', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'13:00', end:'15:00', title:'Meetings',        color:'#6366F1', notify:true,  notifyBefore:5,  sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'15:00', end:'17:00', title:'Admin',           color:'#DDD6FE', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'09:00', end:'12:00', title:'Deep Work',       color:'#818CF8', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'13:00', end:'15:00', title:'Meetings',        color:'#6366F1', notify:true,  notifyBefore:5,  sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'15:00', end:'17:00', title:'Planning',        color:'#8B5CF6', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'09:00', end:'12:00', title:'Deep Work',       color:'#818CF8', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'13:00', end:'15:00', title:'Emails',          color:'#C7D2FE', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'15:00', end:'17:00', title:'Planning',        color:'#8B5CF6', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
    ],
  },
  {
    id: 'parent',
    name: 'Stay-at-Home Parent',
    description: 'Family-centred routine',
    icon: '🏠',
    color: '#EC4899',
    isDefault: true,
    events: [
      { day:'Monday',    start:'06:30', end:'07:00', title:'Morning Routine', color:'#7DD3FC', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'07:00', end:'08:00', title:'Breakfast',       color:'#FDE68A', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'08:00', end:'09:00', title:'School Run',      color:'#F472B6', notify:true,  notifyBefore:15, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'09:00', end:'11:00', title:'Cleaning',        color:'#DB2777', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'13:00', end:'15:00', title:'Meal Prep',       color:'#FBBF24', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'15:00', end:'16:00', title:'School Run',      color:'#F472B6', notify:true,  notifyBefore:15, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'16:00', end:'18:00', title:'Childcare',       color:'#F9A8D4', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'18:00', end:'19:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'19:00', end:'21:00', title:'Family Time',     color:'#BE185D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'08:00', end:'09:00', title:'School Run',      color:'#F472B6', notify:true,  notifyBefore:15, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'09:30', end:'11:00', title:'Gym',             color:'#FB923C', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'13:00', end:'15:00', title:'Errands',         color:'#FBCFE8', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'15:00', end:'16:00', title:'School Run',      color:'#F472B6', notify:true,  notifyBefore:15, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'16:00', end:'19:00', title:'Family Time',     color:'#BE185D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'08:00', end:'09:00', title:'School Run',      color:'#F472B6', notify:true,  notifyBefore:15, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'09:00', end:'12:00', title:'Cleaning',        color:'#DB2777', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'15:00', end:'16:00', title:'School Run',      color:'#F472B6', notify:true,  notifyBefore:15, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'18:00', end:'19:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
    ],
  },
  {
    id: 'fitness',
    name: 'Fitness Enthusiast',
    description: 'Training-centred schedule',
    icon: '💪',
    color: '#F97316',
    isDefault: true,
    events: [
      { day:'Monday',    start:'05:30', end:'06:00', title:'Morning Routine', color:'#7DD3FC', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'06:00', end:'07:30', title:'Back/Biceps',     color:'#FCA5A5', notify:true,  notifyBefore:5,  sound:'default', soundEnabled:true },
      { day:'Monday',    start:'07:30', end:'08:00', title:'Breakfast',       color:'#FDE68A', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'18:00', end:'19:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'21:00', end:'22:00', title:'Stretching',      color:'#FED7AA', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'06:00', end:'07:30', title:'Cardio',          color:'#F97316', notify:true,  notifyBefore:5,  sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'07:30', end:'08:00', title:'Breakfast',       color:'#FDE68A', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'18:00', end:'19:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'06:00', end:'07:30', title:'Legs/Abs',        color:'#FECACA', notify:true,  notifyBefore:5,  sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'07:30', end:'08:00', title:'Breakfast',       color:'#FDE68A', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'18:00', end:'19:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'06:00', end:'07:00', title:'Yoga',            color:'#FDBA74', notify:true,  notifyBefore:5,  sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'07:00', end:'08:00', title:'Breakfast',       color:'#FDE68A', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'18:00', end:'19:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'06:00', end:'07:30', title:'Chest/Shoulders/Triceps', color:'#FEE2E2', notify:true, notifyBefore:5, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'07:30', end:'08:00', title:'Breakfast',       color:'#FDE68A', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'18:00', end:'19:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Saturday',  start:'07:00', end:'09:00', title:'Football Training', color:'#EF4444', notify:true, notifyBefore:15, sound:'default', soundEnabled:true },
      { day:'Saturday',  start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Saturday',  start:'20:00', end:'21:00', title:'Recovery',        color:'#FEF3C7', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Sunday',    start:'09:00', end:'10:00', title:'Yoga',            color:'#FDBA74', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Sunday',    start:'10:00', end:'12:00', title:'Recovery',        color:'#FEF3C7', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
    ],
  },
  {
    id: 'freelancer',
    name: 'Freelancer',
    description: 'Flexible & balanced',
    icon: '🧑‍💻',
    color: '#10B981',
    isDefault: true,
    events: [
      { day:'Monday',    start:'08:00', end:'09:00', title:'Morning Routine', color:'#7DD3FC', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'09:00', end:'12:00', title:'Deep Work',       color:'#818CF8', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'13:00', end:'14:00', title:'Client Call',     color:'#4F46E5', notify:true,  notifyBefore:5,  sound:'default', soundEnabled:true },
      { day:'Monday',    start:'14:00', end:'17:00', title:'Deep Work',       color:'#818CF8', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'17:00', end:'18:00', title:'Emails',          color:'#C7D2FE', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Monday',    start:'19:00', end:'20:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'09:00', end:'12:00', title:'Deep Work',       color:'#818CF8', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'13:00', end:'15:00', title:'Shallow Work',    color:'#A5B4FC', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'15:00', end:'16:00', title:'Admin',           color:'#DDD6FE', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'17:30', end:'19:00', title:'Gym',             color:'#FB923C', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Tuesday',   start:'19:00', end:'20:00', title:'Dinner',          color:'#F59E0B', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'09:00', end:'13:00', title:'Deep Work',       color:'#818CF8', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'13:00', end:'14:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'14:00', end:'15:00', title:'Client Call',     color:'#4F46E5', notify:true,  notifyBefore:5,  sound:'default', soundEnabled:true },
      { day:'Wednesday', start:'15:00', end:'17:00', title:'Content Creation', color:'#7C3AED', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'09:00', end:'12:00', title:'Deep Work',       color:'#818CF8', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'13:00', end:'16:00', title:'Deep Work',       color:'#818CF8', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Thursday',  start:'17:30', end:'19:00', title:'Gym',             color:'#FB923C', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'09:00', end:'12:00', title:'Deep Work',       color:'#818CF8', notify:true,  notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'12:00', end:'13:00', title:'Lunch',           color:'#FCD34D', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'13:00', end:'15:00', title:'Emails',          color:'#C7D2FE', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Friday',    start:'15:00', end:'17:00', title:'Planning',        color:'#8B5CF6', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Saturday',  start:'10:00', end:'12:00', title:'Shallow Work',    color:'#A5B4FC', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Saturday',  start:'14:00', end:'17:00', title:'Free Time',       color:'#BBF7D0', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Sunday',    start:'11:00', end:'13:00', title:'Planning',        color:'#8B5CF6', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
      { day:'Sunday',    start:'14:00', end:'18:00', title:'Free Time',       color:'#BBF7D0', notify:false, notifyBefore:10, sound:'default', soundEnabled:true },
    ],
  },
];

export const TEMPLATES = DEFAULT_TEMPLATES;
